
CREATE DATABASE HOSPITAL;
USE HOSPITAL;


CREATE TABLE PACIENTE (
    Id INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(80) NOT NULL,
    Endereco VARCHAR(100) NOT NULL,
    Idade INT NOT NULL,
    PRIMARY KEY (Id)
);

CREATE TABLE MEDICO (
    Id INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(80) NOT NULL,
    Especialidade VARCHAR(50),
    PRIMARY KEY (Id)
);

CREATE TABLE CONSULTA (
    Id INT NOT NULL AUTO_INCREMENT,
    éRetorno BOOLEAN NOT NULL,
    Paciente_IdPaciente INT NOT NULL,
    Medico_IdMedico INT NOT NULL,
    PRIMARY KEY (Id),
    FOREIGN KEY (Paciente_IdPaciente) REFERENCES PACIENTE(Id),
    FOREIGN KEY (Medico_IdMedico) REFERENCES MEDICO(Id)
);

CREATE TABLE ENCAMINHAMENTO (
    Id INT NOT NULL AUTO_INCREMENT,
    éExame BOOLEAN NOT NULL,
    éCirurgia BOOLEAN NOT NULL,
    Consulta_IdConsulta INT NOT NULL,
    PRIMARY KEY (Id),
    FOREIGN KEY (Consulta_IdConsulta) REFERENCES CONSULTA(Id)
);

CREATE TABLE PRESCRICAO (
    Id INT NOT NULL AUTO_INCREMENT,
    Consulta_IdConsulta INT NOT NULL,
    PRIMARY KEY (Id),
    FOREIGN KEY (Consulta_IdConsulta) REFERENCES CONSULTA(Id)
);

CREATE TABLE CIRURGIA (
    Id INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50),
    PRIMARY KEY (Id)
);

CREATE TABLE EXAME (
    Id INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50),
    PRIMARY KEY (Id)
);

CREATE TABLE MEDICAMENTO (
    Id INT NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50),
    PRIMARY KEY (Id)
);

CREATE TABLE ENCAMINHAMENTO_CIRURGIA (
    Cirurgia_IdCirurgia INT NOT NULL,
    Encaminhamento_IdEncaminhamento INT NOT NULL,
    FOREIGN KEY (Cirurgia_IdCirurgia) REFERENCES CIRURGIA(Id),
    FOREIGN KEY (Encaminhamento_IdEncaminhamento) REFERENCES ENCAMINHAMENTO(Id)
);

CREATE TABLE ENCAMINHAMENTO_EXAME (
    Exame_IdExame INT NOT NULL,
    Encaminhamento_IdEncaminhamento INT NOT NULL,
    FOREIGN KEY (Exame_IdExame) REFERENCES EXAME(Id),
    FOREIGN KEY (Encaminhamento_IdEncaminhamento) REFERENCES ENCAMINHAMENTO(Id)
);

CREATE TABLE PRESCRICAO_MEDICAMENTO (
    Medicamento_IdMedicamento INT NOT NULL,
    Prescricao_IdPrescricao INT NOT NULL,
    FOREIGN KEY (Medicamento_IdMedicamento) REFERENCES MEDICAMENTO(Id),
    FOREIGN KEY (Prescricao_IdPrescricao) REFERENCES PRESCRICAO(Id)
);